site_name: YouQu Docs
copyright: Copyright © 2024 UnionTech Software Technology Co., Ltd. All Rights Reserved.
theme:
  name: material
  language: zh
  custom_dir: docs/overrides
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent:
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  logo: "https://pic.imgdb.cn/item/653095b5c458853aef397f4e.png"
  icon:
    repo: fontawesome/brands/github

repo_name: youqu
repo_url: https://github.com/linuxdeepin/deepin-autotest-framework

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - tables
  - def_list
  - abbr
  - md_in_html
  - footnotes

plugins:
  - git-revision-date-localized:
      locale: zh
      exclude:
        - comments.md
  - git-authors:
  - search
  - mike

extra:
  generator: false
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://mikigo.gitee.io/funny-docs
      name: funny-docs
    - icon: fontawesome/brands/github
      link: https://github.com/linuxdeepin
      name: linuxdeepin
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/youqu
      name: pypi
  homepage: https://linuxdeepin.github.io/deepin-autotest-framework

extra_javascript:
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
  - js/termynal.js
  - js/custom.js

extra_css:
  - stylesheets/extra.css
  - css/termynal.css
  - css/custom.css
  - 'https://ianlunn.github.io/Hover/css/hover.css'

nav:
  - 快速开始: index.md

  - 详细功能:
    - 框架功能介绍/环境部署.md
    - 框架功能介绍/全局配置.md
    - 框架功能介绍/执行管理器.md
    - 框架功能介绍/标签化管理.md
    - 框架功能介绍/标签自动同步.md
    - 框架功能介绍/标签导出.md
    - 框架功能介绍/图像识别.md
    - 框架功能介绍/属性定位.md
    - 框架功能介绍/OCR识别.md
    - 框架功能介绍/相对坐标定位.md
    - 框架功能介绍/去干扰识别.md
    - 框架功能介绍/测试报告.md
    - 框架功能介绍/键鼠操作.md
    - 框架功能介绍/日志系统.md
    - 框架功能介绍/失败录屏.md
    - 框架功能介绍/重启类场景.md
    - 框架功能介绍/PMS数据回填.md
    - 框架功能介绍/Wayland适配.md
    - 框架功能介绍/静态代码扫描.md

  - 框架设计:
    - 自动化测试架构设计v1.0.md
    - AT基础框架设计方案.md
    - AT应用库设计方案.md

  - 规范建议:
    - AT开发规范.md
    - AT经验总结.md
    - AT用例筛选指北.md

  - 技术演进:
    - 智能化功能测试.md
    - 智能化性能测试.md

  - 框架生态:
      - 框架生态.md

  - 版本更新:
    - RELEASE.md

  - 常见问题: 常见问题.md

  - 留言:
      - comments.md